DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
    `id` INT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(255) NOT NULL, `password` VARCHAR(150) NOT NULL, `is_administrator` BOOLEAN
);

CREATE TABLE `menu` (
  `id` INT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(255) NOT NULL, `image` VARCHAR(150) NOT NULL, `price` INT NOT NULL, `description` VARCHAR(150) NOT NULL
);